export {
  PRODUCT_HIGHLIGHT_PANEL_GROUP_ORDER,
  groupProductHighlightPanelFields,
  isProductHighlightPanelField,
  isProductHighlightSectionNodeId,
  isProductHighlightSectionType,
  isProductHighlightSettingsPanelFields,
  prepareProductHighlightSettingsNode,
  productHighlightSettingsBaseFromNodeId,
  productHighlightSiblingPath,
  productHighlightSidebarLabel,
  productHighlightVariantLabel,
  readProductHighlightSettingValue,
  resolveProductHighlightVariant,
  sortProductHighlightPanelFields,
} from '../../../create-theme/sidebar/theme-editor-product-highlight-panel.utils';
