export const INDIAN_BANKS = [
  'State Bank of India',
  'HDFC Bank',
  'ICICI Bank',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'Punjab National Bank',
  'Bank of Baroda',
  'Canara Bank',
  'Union Bank of India',
  'Indian Bank',
  'Bank of India',
  'Central Bank of India',
  'Indian Overseas Bank',
  'UCO Bank',
  'Bank of Maharashtra',
  'Punjab & Sind Bank',
  'IDBI Bank',
  'Yes Bank',
  'IndusInd Bank',
  'Federal Bank',
  'RBL Bank',
  'Bandhan Bank',
  'IDFC FIRST Bank',
  'AU Small Finance Bank',
  'Karur Vysya Bank',
  'South Indian Bank',
  'City Union Bank',
  'Tamilnad Mercantile Bank',
  'Karnataka Bank',
  'Jammu & Kashmir Bank',
] as const;
