export enum CustomerNotifications {
  OrderConfirmation = 'Order confirmation',
  DraftOrderInvoice = 'Draft order invoice',
  ShippingConfirmation = 'Shipping confirmation',
  ReadyForLocalPickup = 'Ready for local pickup',
  PickedUpByCustomer = 'Picked up by customer',
  OrderOutForLocalDelivery = 'Order out for local delivery',
  OrderLocallyDelivered = 'Order locally delivered',
  OrderMissedLocalDelivery = 'Order missed local delivery',
  NewGiftCard = 'New gift card',
  GiftCardReceipt = 'Gift card receipt',
  StoreCreditIssued = 'Store credit issued',
  OrderInvoice = 'Order invoice',
  OrderEdited = 'Order edited',
  OrderCanceled = 'Order canceled',
  OrderPaymentReceipt = 'Order payment receipt',
  OrderRefund = 'Order refund',
  OrderLink = 'Order link',
  PaymentError = 'Payment error',
  PendingPaymentError = 'Pending payment error',
  PendingPaymentSuccess = 'Pending payment success',
  PaymentReminder = 'Payment reminder',
  ShippingUpdate = 'Shipping update',
  OutForDelivery = 'Out for delivery',
  Delivered = 'Delivered',
  ReturnCreated = 'Return created',
  OrderLevelReturnLabelCreated = 'Order-level return label created',
  ReturnRequestReceived = 'Return request received',
  ReturnRequestApproved = 'Return request approved',
  ReturnRequestDeclined = 'Return request declined',
  CustomerAccountInvite = 'Customer account invite',
  CustomerAccountWelcome = 'Customer account welcome',
  CustomerAccountPasswordReset = 'Customer account password reset',
  ContactCustomer = 'Contact customer',
  CustomerEmailAddressChangeConfirmation = 'Customer email address change confirmation',
}


