/** Preview slide metadata for create-theme add-section modal (rewritten from dev catalog). */
import type { SectionPreviewVariant } from './SectionPreviewVisual';

export type BlockPreviewSlide = {
  id: string;
  headline: string;
  headlineAccent: string;
  caption: string;
  variant: SectionPreviewVariant;
};

export const BLOCK_PREVIEW_SLIDES: BlockPreviewSlide[] = [
  {
    id: 'before-after',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'A before/after image slider',
    variant: 'before-after',
  },
  {
    id: 'product-card',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'A holographic product card',
    variant: 'product-card',
  },
  {
    id: 'text-block',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Rich text and headings for any section',
    variant: 'text-block',
  },
  {
    id: 'newsletter',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Collect emails with a signup form',
    variant: 'newsletter',
  },
  {
    id: 'contact-form',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Let customers send you a message',
    variant: 'contact-form',
  },
  {
    id: 'custom-section',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Build a section with blocks and settings',
    variant: 'custom-section',
  },
  {
    id: 'featured-collection-carousel',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Featured collection: Carousel',
    variant: 'featured-collection-carousel',
  },
  {
    id: 'featured-collection-editorial',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Featured collection: Editorial',
    variant: 'featured-collection-editorial',
  },
  {
    id: 'featured-collection-grid',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Featured collection: Grid',
    variant: 'featured-collection-grid',
  },
  {
    id: 'featured-product',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Featured product',
    variant: 'featured-product',
  },
  {
    id: 'product-highlight',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Product highlight',
    variant: 'product-highlight',
  },
  {
    id: 'product-hotspots',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Product hotspots',
    variant: 'product-hotspots',
  },
  {
    id: 'recommended-products',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Recommended products',
    variant: 'recommended-products',
  },
  {
    id: 'blog-posts-carousel',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Blog posts: Carousel',
    variant: 'blog-posts-carousel',
  },
  {
    id: 'blog-posts-editorial',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Blog posts: Editorial',
    variant: 'blog-posts-editorial',
  },
  {
    id: 'blog-posts-grid',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Blog posts: Grid',
    variant: 'blog-posts-grid',
  },
  {
    id: 'storytelling-carousel',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Carousel',
    variant: 'storytelling-carousel',
  },
  {
    id: 'storytelling-editorial',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Editorial',
    variant: 'storytelling-editorial',
  },
  {
    id: 'storytelling-editorial-jumbo',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Editorial: Jumbo text',
    variant: 'storytelling-editorial-jumbo',
  },
  {
    id: 'image-compare',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Image compare',
    variant: 'image-compare',
  },
  {
    id: 'image-with-text',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Image with text',
    variant: 'image-with-text',
  },
  {
    id: 'storytelling-video',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Video',
    variant: 'storytelling-video',
  },
  {
    id: 'storytelling-logo',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Logo',
    variant: 'storytelling-logo',
  },
  {
    id: 'faq',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'FAQ',
    variant: 'faq',
  },
  {
    id: 'icons-with-text',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Icons with text',
    variant: 'icons-with-text',
  },
  {
    id: 'text-marquee',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Marquee',
    variant: 'text-marquee',
  },
  {
    id: 'multicolumn',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Multicolumn',
    variant: 'multicolumn',
  },
  {
    id: 'pull-quote',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Pull quote',
    variant: 'pull-quote',
  },
  {
    id: 'rich-text',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Rich text',
    variant: 'rich-text',
  },
  {
    id: 'footer-section',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Join our email list, email signup, and store links',
    variant: 'footer-section',
  },
  {
    id: 'policies-links',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Policies and links',
    variant: 'policies-links',
  },
  {
    id: 'announcement-bar',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Share promotions and store news at the top of every page',
    variant: 'announcement-bar',
  },
  {
    id: 'divider',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'A horizontal line to separate content',
    variant: 'divider',
  },
  {
    id: 'hero',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Large heading area with buttons and imagery',
    variant: 'hero',
  },
  {
    id: 'hero-bottom-aligned',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Hero: Bottom aligned',
    variant: 'hero-bottom-aligned',
  },
  {
    id: 'hero-marquee',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Hero: Marquee',
    variant: 'hero-marquee',
  },
  {
    id: 'large-logo',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Large logo',
    variant: 'large-logo',
  },
  {
    id: 'layered-slideshow',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Layered slideshow',
    variant: 'layered-slideshow',
  },
  {
    id: 'slideshow-full-frame',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Slideshow: Full frame',
    variant: 'slideshow-full-frame',
  },
  {
    id: 'slideshow-inset',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Slideshow: Inset',
    variant: 'slideshow-inset',
  },
  {
    id: 'split-showcase',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Split showcase',
    variant: 'split-showcase',
  },
  {
    id: 'collection-links-spotlight',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Collection links: Spotlight',
    variant: 'collection-links-spotlight',
  },
  {
    id: 'collection-links-text',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Collection links: Text',
    variant: 'collection-links-text',
  },
  {
    id: 'collection-list-bento',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Collection list: Bento',
    variant: 'collection-list-bento',
  },
  {
    id: 'collection-list-carousel',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Collection list: Carousel',
    variant: 'collection-list-carousel',
  },
  {
    id: 'collection-list-editorial',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Collection list: Editorial',
    variant: 'collection-list-editorial',
  },
  {
    id: 'collection-list-grid',
    headline: 'Have an idea?',
    headlineAccent: "Let's bring it to life",
    caption: 'Collection list: Grid',
    variant: 'collection-list-grid',
  },
];
