const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const SystemSettings = require('../models/SystemSettings');

// Generates a quotation/invoice PDF; returns { url, filename }.
async function generateInvoicePdf({ workspace, contact, docType, items, gstPercent, notes }) {
  const dir = path.join(__dirname, '..', '..', 'uploads', 'invoices');
  fs.mkdirSync(dir, { recursive: true });
  const num = `${docType === 'quotation' ? 'QT' : 'INV'}-${Date.now().toString().slice(-8)}`;
  const filename = `${num}.pdf`;
  const filePath = path.join(dir, filename);

  const settings = await SystemSettings.findOne();
  const brand = (settings && settings.appName) || workspace.name || 'Codiic Panel';

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  const title = docType === 'quotation' ? 'QUOTATION' : 'INVOICE';
  doc.fontSize(20).font('Helvetica-Bold').fillColor('#059669').text(workspace.name || 'Business', { align: 'left' });
  doc.moveDown(0.3);
  doc.fontSize(16).fillColor('#111').text(title, { align: 'right' });
  doc.fontSize(10).font('Helvetica').fillColor('#555')
    .text(`${title === 'INVOICE' ? 'Invoice' : 'Quotation'} No: ${num}`, { align: 'right' })
    .text(`Date: ${new Date().toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', day: '2-digit', month: 'short', year: 'numeric' })}`, { align: 'right' });
  doc.moveDown(1);

  doc.fontSize(11).font('Helvetica-Bold').fillColor('#111').text('Bill To:');
  doc.fontSize(10).font('Helvetica').fillColor('#333')
    .text(contact?.name || 'Customer')
    .text(contact?.phone ? `+${contact.phone}` : '');
  doc.moveDown(1);

  // Table header
  const tableTop = doc.y;
  const colX = { sn: 50, name: 80, qty: 330, price: 390, amt: 470 };
  doc.rect(50, tableTop - 4, 495, 20).fill('#059669');
  doc.fillColor('#fff').font('Helvetica-Bold').fontSize(10);
  doc.text('#', colX.sn + 4, tableTop);
  doc.text('Item', colX.name, tableTop);
  doc.text('Qty', colX.qty, tableTop);
  doc.text('Price (Rs.)', colX.price, tableTop);
  doc.text('Amount (Rs.)', colX.amt, tableTop);

  let y = tableTop + 24;
  let subtotal = 0;
  doc.font('Helvetica').fontSize(10).fillColor('#333');
  items.forEach((it, i) => {
    const qty = Number(it.qty) || 1;
    const price = Number(it.price) || 0;
    const amt = qty * price;
    subtotal += amt;
    if (i % 2 === 1) { doc.rect(50, y - 4, 495, 20).fill('#f3f4f6'); doc.fillColor('#333'); }
    doc.text(String(i + 1), colX.sn + 4, y);
    doc.text(String(it.name || '').slice(0, 45), colX.name, y);
    doc.text(String(qty), colX.qty, y);
    doc.text(price.toFixed(2), colX.price, y);
    doc.text(amt.toFixed(2), colX.amt, y);
    y += 22;
  });

  y += 10;
  const gst = (Number(gstPercent) || 0) * subtotal / 100;
  const total = subtotal + gst;
  doc.font('Helvetica').fontSize(10).fillColor('#333');
  doc.text('Subtotal:', colX.price, y); doc.text(`Rs. ${subtotal.toFixed(2)}`, colX.amt, y); y += 16;
  if (gst > 0) { doc.text(`GST (${gstPercent}%):`, colX.price, y); doc.text(`Rs. ${gst.toFixed(2)}`, colX.amt, y); y += 16; }
  doc.font('Helvetica-Bold').fontSize(12).fillColor('#059669');
  doc.text('Total:', colX.price, y); doc.text(`Rs. ${total.toFixed(2)}`, colX.amt, y);

  if (notes) {
    doc.moveDown(2);
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#111').text('Notes:', 50);
    doc.font('Helvetica').fontSize(9).fillColor('#555').text(notes, 50);
  }

  doc.fontSize(8).fillColor('#999').text(`Generated by ${brand}`, 50, 780, { align: 'center', width: 495 });
  doc.end();
  await new Promise((resolve, reject) => { stream.on('finish', resolve); stream.on('error', reject); });

  // Use the /api/uploads path: every install proxies /api to this backend, whereas
  // bare /uploads is routed to the frontend on some panels (WhatsApp then can't
  // fetch the PDF and the send fails).
  const base = (process.env.BACKEND_URL || 'https://api.wabapanel.com').replace(/\/+$/, '');
  const url = `${base}/api/uploads/invoices/${filename}`;
  return { url, filename, num, total };
}

module.exports = { generateInvoicePdf };
