const SAMPLE_VARIABLES: Record<string, string> = {
  customer_name: 'John Doe',
  order_number: '9999',
  store_name: 'My Store',
  view_order_url: '#',
  confirm_order_url: '#',
  store_url: '#',
  reservation_deadline: 'June 26, 2026 at 12:46 am',
  order_total: 'Rs. 439.35',
  tracking_url: '#',
  carrier_name: 'UPS',
  support_email: 'support@example.com',
  return_tracking_url: '#',
  return_label_url: '#',
  account_invite_url: '#',
  account_url: '#',
  password_reset_url: '#',
  new_email: 'newemail@example.com',
  message_body: 'Your message here',
  gift_card_code: 'A1B2 3C4D 5E6F 7G8H',
  gift_card_amount: 'Rs. 100',
  gift_card_amount_formatted: 'Rs. 100.00 INR',
  gift_card_balance_url: '#',
  recipient_name: 'Jane Doe',
  credit_amount: 'Rs. 50.00',
  amount_due: 'Rs. 404.95',
  amount_paid: 'Rs. 404.95',
  refund_amount: 'Rs. 404.95',
  pay_now_url: '#',
  return_to_cart_url: '#',
  order_status_url: '#',
  pickup_location: 'Main Street Store',
  pickup_location_name: 'Example Shop',
  pickup_address_line1: '34 Example Street',
  pickup_address_line2: 'Next to example',
  pickup_city: 'Ottawa',
  pickup_state: 'Ontario',
  pickup_zip: 'K1N5TS',
  pickup_map_url: '#',
  delivery_name: 'Jane Customer',
  delivery_address_line1: '123 Delivery Street',
  delivery_address_line2: 'Apt 4B',
  delivery_city: 'Ottawa',
  delivery_state: 'Ontario',
  delivery_zip: 'K1N5TS',
  shipping_name: 'Steve Shipper',
  shipping_address_line1: '123 Shipping Street',
  shipping_city: 'Shippington',
  shipping_state: 'Kentucky',
  shipping_zip: '40003',
  shipping_country: 'United States',
  shipping_phone: '555-555-SHIP',
  shipping_method: 'Standard',
  tracking_number: '1Z999AA10123456784',
  customer_email: 'jon@example.com',
};

export function replaceNotificationTemplateVariables(text: string): string {
  let result = text;
  for (const [key, value] of Object.entries(SAMPLE_VARIABLES)) {
    result = result.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), value);
  }
  return result;
}
