// Standard world currency catalogue used to bulk-seed SystemSettings.currencies.
// `rate` = approximate units of this currency per 1 INR (base), used only when a
// plan uses exchange-rate pricing. Rates are seed defaults — admin should review
// and update them in Admin → Currencies. 0 = no rate set (admin must fill in).
module.exports = [
  { code: 'INR', name: 'Indian Rupee', symbol: '\u20b9', rate: 1 },
  { code: 'USD', name: 'US Dollar', symbol: '$', rate: 0.012 },
  { code: 'EUR', name: 'Euro', symbol: '\u20ac', rate: 0.011 },
  { code: 'GBP', name: 'British Pound', symbol: '\u00a3', rate: 0.0095 },
  { code: 'AED', name: 'UAE Dirham', symbol: '\u062f.\u0625', rate: 0.044 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '\ufdfc', rate: 0.045 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rate: 0.018 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', rate: 0.016 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rate: 0.016 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rate: 0.056 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '\u00a5', rate: 1.85 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '\u00a5', rate: 0.087 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', rate: 0.094 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', rate: 0.02 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', rate: 0.22 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '\u0631.\u0642', rate: 0.044 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: '\u062f.\u0643', rate: 0.0037 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.\u062f.\u0628', rate: 0.0045 },
  { code: 'OMR', name: 'Omani Rial', symbol: '\u0631.\u0639.', rate: 0.0046 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '\u09f3', rate: 1.32 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '\u20a8', rate: 3.35 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', rate: 3.6 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs', rate: 1.6 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rate: 190 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '\u20b1', rate: 0.68 },
  { code: 'THB', name: 'Thai Baht', symbol: '\u0e3f', rate: 0.43 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '\u20ab', rate: 300 },
  { code: 'KRW', name: 'South Korean Won', symbol: '\u20a9', rate: 16.5 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '\u20ba', rate: 0.41 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '\u20bd', rate: 1.1 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', rate: 0.067 },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$', rate: 0.22 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', rate: 12 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '\u20a6', rate: 19 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', rate: 1.55 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '\u00a3', rate: 0.59 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '\u20b5', rate: 0.18 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rate: 0.0105 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rate: 0.125 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rate: 0.128 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rate: 0.082 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'z\u0142', rate: 0.047 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'K\u010d', rate: 0.27 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', rate: 4.3 },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '\u20aa', rate: 0.044 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: '\u062f.\u0645.', rate: 0.12 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '\u20a8', rate: 0.55 },
];
