const mongoose = require('mongoose');

const botFlowSchema = new mongoose.Schema({
  workspace: { type: mongoose.Schema.Types.ObjectId, ref: 'Workspace', required: true },
  name: { type: String, required: true },
  triggerKeywords: [{ type: String }],
  matchType: { type: String, enum: ['exact', 'contains'], default: 'exact' },
  eventTrigger: { type: String, enum: ['', 'dnp', 'new_lead'], default: '' },
  isActive: { type: Boolean, default: false },
  runs: { type: Number, default: 0 },
  nodeHits: { type: Map, of: Number, default: {} },
  startNode: { type: String, default: '' },
  startX: { type: Number, default: 40 },
  startY: { type: Number, default: 60 },
  nodes: [{
    id: { type: String, required: true },
    name: { type: String, default: '' },
    type: { type: String, enum: ['text', 'media', 'interactive', 'template', 'action', 'products', 'webhook', 'question', 'delay', 'condition'], default: 'text' },
    productIds: [{ type: String }],
    actionType: { type: String, enum: ['book_appointment', 'add_tag', 'assign_agent', 'ai_on', 'ai_off', 'send_payment'], default: 'book_appointment' },
    payAmount: { type: Number, default: 0 },
    payDesc: { type: String, default: '' },
    payMethod: { type: String, enum: ['razorpay', 'upi'], default: 'razorpay' },
    payUpiId: { type: String, default: '' },
    actionTag: { type: String, default: '' },
    actionAgent: { type: String, default: '' },
    apptTitle: { type: String, default: '' },
    apptDaysAhead: { type: Number, default: 1 },
    apptTime: { type: String, default: '10:00' },
    apptDuration: { type: Number, default: 30 },
    apptDayEnd: { type: String, default: '18:00' },
    apptMode: { type: String, enum: ['auto', 'choose'], default: 'auto' },
    text: { type: String, default: '' },
    mediaType: { type: String, default: 'image' },
    mediaUrl: { type: String, default: '' },
    caption: { type: String, default: '' },
    header: { type: String, default: '' },
    headerType: { type: String, enum: ['none', 'text', 'image', 'video', 'document'], default: 'none' },
    headerMediaUrl: { type: String, default: '' },
    footer: { type: String, default: '' },
    mode: { type: String, enum: ['buttons', 'list', 'cta'], default: 'buttons' },
    ctaText: { type: String, default: '' },
    ctaUrl: { type: String, default: '' },
    ctas: [{ text: { type: String, default: '' }, url: { type: String, default: '' } }],
    buttons: [{ title: { type: String, default: '' }, next: { type: String, default: '' } }],
    listButtonText: { type: String, default: '' },
    rows: [{ title: { type: String, default: '' }, description: { type: String, default: '' }, next: { type: String, default: '' } }],
    templateName: { type: String, default: '' },
    templateLanguage: { type: String, default: 'en' },
    answerVar: { type: String, default: '' },
    waitTimeoutHours: { type: Number, default: 0 },
    nextTimeout: { type: String, default: '' },
    delaySeconds: { type: Number, default: 0 },
    delayUnit: { type: String, enum: ['seconds', 'minutes', 'hours', 'days'], default: 'seconds' },
    condField: { type: String, enum: ['reply', 'tag', 'variable'], default: 'reply' },
    condVarName: { type: String, default: '' },
    condOp: { type: String, enum: ['equals', 'contains', 'exists'], default: 'contains' },
    condValue: { type: String, default: '' },
    nextTrue: { type: String, default: '' },
    nextFalse: { type: String, default: '' },
    webhookUrl: { type: String, default: '' },
    webhookMethod: { type: String, default: 'POST' },
    webhookHeaders: [{ key: { type: String, default: '' }, value: { type: String, default: '' } }],
    webhookBody: { type: String, default: '' },
    next: { type: String, default: '' },
    x: { type: Number, default: 0 },
    y: { type: Number, default: 0 },
  }],
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });

botFlowSchema.index({ workspace: 1, isActive: 1 });

module.exports = mongoose.model('BotFlow', botFlowSchema);
