module.exports = {
  User: require('./User'),
  Workspace: require('./Workspace'),
  Plan: require('./Plan'),
  Contact: require('./Contact'),
  Segment: require('./Segment'),
  Tag: require('./Tag'),
  Template: require('./Template'),
  Campaign: require('./Campaign'),
  Conversation: require('./Conversation'),
  Message: require('./Message'),
  Automation: require('./Automation'),
  Team: require('./Team'),
  Payment: require('./Payment'),
  WalletTransaction: require('./WalletTransaction'),
  MetaPricing: require('./MetaPricing'),
  Pipeline: require('./Pipeline'),
  Form: require('./Form'),
  ShortLink: require('./ShortLink'),
  Appointment: require('./Appointment'),
  LandingPage: require('./LandingPage'),
  SystemSettings: require('./SystemSettings'),
  Permission: require('./Permission'),
  Inquiry: require('./Inquiry'),
  QuickReply: require('./QuickReply'),
};
